name: Receive Push Event

on:
  repository_dispatch:
    types: [my-push-event]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: run-cmd
      working-directory: jpgramma
      run: |
        pwd
